[package]
name = "usc-light-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
macroquad = { version = "0.3.8", default-features = false }
once_cell = "1.12.0"